name: Deploy PD Twitch Chat Toxicity API

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:   
      - name: ENTRECOT DEPLOY
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.HOST}} 
          user: ${{secrets.USERNAME}} 
          private_key: ${{secrets.KEY}} 
          command: |
            cd twitch-chat-toxicity &&
            git pull origin main &&
            npm prune &&
            cd api &&
            npm install &&
            pm2 restart twitch_chat_toxicity_api
